# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='ulr',
            new_name='url',
        ),
    ]
